### ISSUE TITLE
Http*Challenge: checkConfiguration should ignore certificate verification errors

### ISSUE THREAD

**Issue by alexzorin** [mlocati/concrete5_acme#3]
Reported on the [Let's Encrypt community forums](https://community.letsencrypt.org/t/peers-certificate-issuer-is-not-recognized/112000), it seems that the preflight performed for the `HttpPhysicalChallenge` runs, at least under some configurations, with `CURLOPT_SSL_VERIFYHOST = 2`.

This can be a problem if there a redirect to an HTTPS host that has e.g. a self-signed certificate.

Common implementations of RFC8555 (Boulder, Pebble) do not do any certification verification when encountering these kinds of redirects.

Since the preflight in `checkConfiguration` does perform certificate verification, it can prevent certificate issuance from succeeding where it would otherwise work just fine.

My suggestion would be to set it to 0 indiscriminately.

**Comment by mlocati** [comment]
Yep, you are right.

When I implemented the HTTP authorization, I read [this RFC8555 section](https://tools.ietf.org/html/rfc8555#section-8.3) where we have

> Because many web servers
> allocate a default HTTPS virtual host to a particular low-privilege
> tenant user in a subtle and non-intuitive manner, the challenge must
> be completed over HTTP, not HTTPS.

But of course the web server can send a redirect to HTTPS, and we have to obey that and accept unsafe HTTPS certificates, like Boulder does (see [here](https://github.com/letsencrypt/boulder/blob/release-2020-01-28/va/http.go#L26) and [here](https://github.com/letsencrypt/boulder/blob/release-2020-01-28/va/http.go#L147)).

Could you check if #4 fixes this issue?

**Comment by alexzorin** [comment]
Looks good, thanks!

**Comment by mlocati** [comment]
@alexzorin I just released version 4.2.8 (both in the [concrete5 marketplace](https://www.concrete5.org/marketplace/addons/acme) and on [packagist](https://packagist.org/packages/mlocati-concrete5-packages/acme)) with the fix for this issue.
