### ISSUE TITLE
Add Certificate button doesn't show when there are no certificates

### ISSUE THREAD

**Issue by carlremy** [mlocati/concrete5_acme#5]
The script returns at line 104, so the `<script>` content never runs, and the elements with class `.acme-loading-hide` are never loaded

https://github.com/concrete5-community/acme/blob/dc8ad647cc5133dd4334eea67d398b29cffc34ee/single_pages/dashboard/system/acme/certificates.php#L104

**Comment by mlocati** [comment]
Fixed by https://github.com/concrete5-community/acme/commit/c83ba9686834ac64374e96918c289bb8954cec8a
